### ISSUE TITLE
Missing checkout field labels with Thrivesuite is active

### ISSUE THREAD

**Issue by ludwikc** [helgatheviking/wc-remove-billing-address-on-free-checkout#1]
![de81f523-350c-4a63-b142-ea2c348b7349](https://user-images.githubusercontent.com/9521799/155301801-fcc6641e-7e98-423b-b2be-ecd3a69519bb.png)

**Comment by ludwikc** [comment]
I use ThriveSuite on my Wordpress site (it's an alternative to e.g. Elementor). After activating the plugin, fields are still there, they are just left without any labels, descriptions and placeholders. I've trying to fix it myself, failed, and then reached out to ThriveSuite support and here's the answer I got from them: 
----
I activated the Remove WooCommerce billing address for free checkout plugin. Indeed, the fields are still displaying as seen here https://share.getcloudapp.com/L1uWWbzG
We can't guarantee its compatibility with Thrive products, since we don't have an integration with the said plugin.
I compare the fields using Thrive Theme Builder only and with Remove WooCommerce billing address for free checkout plugin. Both are using the same IDs for the fields. After the test, I deactivate the Remove WooCommerce billing address for free checkout plugin.
Please see:
w/o the plugin: https://share.getcloudapp.com/kpu44Zey
﻿with the plugin: https://share.getcloudapp.com/z8ukkoRn
I also did not see errors associated with Thrive products and the third-party plugin. Please see:
https://share.getcloudapp.com/JruGGZlk

**Comment by helgatheviking** [comment]
Is the SQL Bootcamp free _and_ virtual? If the cart needs shipping it will still ask for an address. Hidden labels seems like a CSS issue... do you have custom CSS somewhere that is accidentally hiding the labels? 

I am not familiar with ThriveSuite and so I don't how their plugin works. I am going to have to say something pretty similar to them... I can't guarantee compatibility with other plugins. 

This plugin is only a single snippet wrapped up as a plugin. I'm filtering [`woocommerce_billing_fields`](https://github.com/helgatheviking/wc-remove-billing-address-on-free-checkout/blob/trunk/wc-remove-billing-address-on-free-checkout.php#L59)

If they are doing something on the same filter, it could conflict. You can try changing the priority of 

```
add_filter( 'woocommerce_billing_fields', 'kia_remove_billing_address_fields_for_free_checkout' );
```

to

```
add_filter( 'woocommerce_billing_fields', 'kia_remove_billing_address_fields_for_free_checkout', 99 );
```

To see if that helps.

**Comment by ludwikc** [comment]
Thanks for the response, Kathy. 

Labels are being hidden only after your plugin is activated and the Cart value is 0. So it's like the plugin is working but it's not hiding the input field but only the labels: https://siadlak.com/product/sqlbootcamp-online/ 

I've tried changing the priority, unfortunately it didn't help neither.

**Comment by helgatheviking** [comment]
Is that the checkout block by any chance? At this point, I can only recommend going through a standard debug procedure of switching to a default theme, and disabling plugins one at a time.  Is there anything else filtering `woocommerce_billing_fields` ?

**Comment by helgatheviking** [comment]
I was able to get my hands on a copy of a Thrive theme with the theme builder component. I found that you can toggle the visibility of the default fields in the builder UI:

![image](https://user-images.githubusercontent.com/507025/160648685-b15203f3-8ad2-4ce6-9ec2-47e91a2166a8.png)

And I found that they are filtering `woocommerce_checkout_fields` with this callback in `integrations/woocommerce/class-filters.php`:

![image](https://user-images.githubusercontent.com/507025/160655228-e03d67b6-e0b2-4127-b161-6042496a1a75.png)

This is relevant because they appear to be pulling from the _saved_ fields from screenshot one and not checking if that field actually exists before adding a priority.

>We can't guarantee its compatibility with Thrive products, since we don't have an integration with the said plugin.

They don't actually need a special integration. They need to not assume the fields are present in the array, when they may have been modified by external code.

I _think_ if they replace this line:
```
$billing_fields[ $key ]['priority'] = $field['priority'];
```

with this:

```
if ( isset( $billing_fields[ $key ] ) ) {
    $billing_fields[ $key ]['priority'] = $field['priority'];
}
```

They can restore compatibility. By not checking if the key exists in the fields array they are restoring an incomplete field.. hence the missing labels. (priority is defined, but label text is not)

I am going to close this as this is not possible to fix in my plugin and must be fixed on their side. They will need to re-write their callback in a way that is compatible with other plugins/snippets also filtering the checkout fields. I think the above may be all that is required to solve it (at least it resolves it for my test site), but also did not test it super thoroughly.
